<a href="https://colab.research.google.com/github/Hhh-1234/python/blob/main/Api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
9f67b856

In [ ]:
import requests #HTTPS 요청을 보내기 위한 requests 라이브러리
import pandas as pd
import pprint

In [ ]:
import requests #HTTPS 요청을 보내기 위한 requests 라이브러리
url = "https://www.omdbapi.com/"
params = { # api 요청의 필요한 파라미트를 딕셔너리로 정의
    "apikey":"9f67b856",
           "t": "Avengers",
           "type": "movie",
           "y": '2012'
}
# GET 요청
response = requests.get(url, params=params)
print (response) # HTTP 응답 상태 코드(예: 200은 성공)를 출력

<Response [200]>

In [ ]:
import pprint
# json 응답을 파이썬 겍채로 변환
data = response.json() # 응답 본문을 JSON 형식으로 파싱하여
pprint.pprint(data)

{'Actors': 'Robert Downey Jr., Chris Evans, Scarlett Johansson',
 'Awards': 'Nominated for 1 Oscar. 40 wins & 81 nominations total',
 'BoxOffice': '$623,357,910',
 'Country': 'United States',
 'DVD': 'N/A',
 'Director': 'Joss Whedon',
 'Genre': 'Action, Sci-Fi',
 'Language': 'English, Russian',
 'Metascore': '69',
 'Plot': "Earth's mightiest heroes must come together and learn to fight as a "
         'team if they are going to stop the mischievous Loki and his alien '
         'army from enslaving humanity.',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg',
 'Production': 'N/A',
 'Rated': 'PG-13',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'},
             {'Source': 'Rotten Tomatoes', 'Value': '91%'},
             {'Source': 'Metacritic', 'Value': '69/100'}],
 'Released': '04 May 2012',
 'Response': 'True',
 'Runtime': '143 min',
 'Title': 'The Avengers',
 'Type': 'movie',
 'Website': 'N/A',
 'Writer': 'Joss Whedon, Zak Penn',
 'Year': '2012',
 'imdbID': 'tt0848228',
 'imdbRating': '8.0',
 'imdbVotes': '1,547,278'}

In [ ]:
import requests
url = "https://www.omdbapi.com/"
params = {
    "apikey": "9f67b856",
    "s" : "Avengers",# t 대신 s 사용 - 제목에 avengers 포함된 영화 전부 검색
    "type" : "movie"
}

response = requests.get(url, params=params)
data = response.json()
data

{'Search': [{'Title': 'The Avengers',
   'Year': '2012',
   'imdbID': 'tt0848228',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'Avengers: Endgame',
   'Year': '2019',
   'imdbID': 'tt4154796',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg'},
  {'Title': 'Avengers: Infinity War',
   'Year': '2018',
   'imdbID': 'tt4154756',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg'},
  {'Title': 'Avengers: Age of Ultron',
   'Year': '2015',
   'imdbID': 'tt2395427',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BODBhYTg1NGQtNGVmNS00ZTdiLThjYTYtZDFkNzRiNTZmNDZjXkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'The Avengers',
   'Year': '1998',
   'imdbID': 'tt0118661',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BZTA4ZmZlZWQtZDRlYS00ZWZhLTk0MzEtYjExMGIzMTBlZDNlXkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'Ultimate Avengers: The Movie',
   'Year': '2006',
   'imdbID': 'tt0491703',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTYyMjk0NTMwMl5BMl5BanBnXkFtZTgwNzY0NjAwNzE@._V1_SX300.jpg'},
  {'Title': 'Ultimate Avengers II',
   'Year': '2006',
   'imdbID': 'tt0803093',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BZjI3MTI5ZTYtZmNmNy00OGZmLTlhNWMtNjZiYmYzNDhlOGRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg'},
  {'Title': 'Next Avengers: Heroes of Tomorrow',
   'Year': '2008',
   'imdbID': 'tt1259998',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTQ3NjExNjY4N15BMl5BanBnXkFtZTcwNTczODkwNQ@@._V1_SX300.jpg'},
  {'Title': 'Avengers Confidential: Black Widow & Punisher',
   'Year': '2014',
   'imdbID': 'tt3482378',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTU2MDg0Njk4MF5BMl5BanBnXkFtZTgwMTY0OTIyMTE@._V1_SX300.jpg'},
  {'Title': 'Crippled Avengers',
   'Year': '1978',
   'imdbID': 'tt0077292',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BYjU2ODU5NzMtMzQ2NC00MmI5LWI1NjMtNmRmMjMzOTMxNWZhXkEyXkFqcGc@._V1_SX300.jpg'}],
 'totalResults': '134',
 'Response': 'True'}

In [ ]:
#검색결과 리스트 출력
movies = data["Search"] # 'search' 대신 'Search' 사용, 변수명도 'movies'로 변경
for movie in movies:
  print(movie['Title'], movie['Year']) # 괄호 오류 수정 및 'title', 'year' 대신 'Title', 'Year' 사용

The Avengers 2012
Avengers: Endgame 2019
Avengers: Infinity War 2018
Avengers: Age of Ultron 2015
The Avengers 1998
Ultimate Avengers: The Movie 2006
Ultimate Avengers II 2006
Next Avengers: Heroes of Tomorrow 2008
Avengers Confidential: Black Widow & Punisher 2014
Crippled Avengers 1978

In [ ]:
import pandas as pd

if 'Search' in data: # 'search' 대신 'Search' 사용
  m_df = pd.DataFrame(data['Search'])
else:
  m_df = pd.DataFrame([data]) # 'Search' 키가 없으면, data자체가 단일 객체이므로 리스트로 감싸서 dataframe으로 만듭니다.

display(m_df.head()) # .head 뒤에 괄호 추가

,Title,Year,imdbID,Type,Poster
0,The Avengers,2012,tt0848228,movie,https://m.media-amazon.com/images/M/MV5BNGE0YT...
1,Avengers: Endgame,2019,tt4154796,movie,https://m.media-amazon.com/images/M/MV5BMTc5MD...
2,Avengers: Infinity War,2018,tt4154756,movie,https://m.media-amazon.com/images/M/MV5BMjMxNj...
3,Avengers: Age of Ultron,2015,tt2395427,movie,https://m.media-amazon.com/images/M/MV5BODBhYT...
4,The Avengers,1998,tt0118661,movie,https://m.media-amazon.com/images/M/MV5BZTA4Zm...

In [ ]:
m_df = m_df.iloc[0:4]# 인덱스 0부터 3까지의 행만 선택합니다.
display(m_df)

,Title,Year,imdbID,Type,Poster
0,The Avengers,2012,tt0848228,movie,https://m.media-amazon.com/images/M/MV5BNGE0YT...
1,Avengers: Endgame,2019,tt4154796,movie,https://m.media-amazon.com/images/M/MV5BMTc5MD...
2,Avengers: Infinity War,2018,tt4154756,movie,https://m.media-amazon.com/images/M/MV5BMjMxNj...
3,Avengers: Age of Ultron,2015,tt2395427,movie,https://m.media-amazon.com/images/M/MV5BODBhYT...

In [ ]:
# 어벤져스 시리즈 4변 정보 수정
titles = [(row['Title'], row['Year']) for index, row in m_df.iterrows()]
print(titles)
# 각 영화 정보를 저장할 빈 리스트
rows = []
url = "https://www.omdbapi.com/"
for title_name, year_value in titles:
  params = {
      "apikey" : "9f67b856",
      "t" : title_name,
      "type" : "movie",
      "y" : year_value
  }
  response = requests.get(url,params=params)
  data = response.json()
  rows.append({
      'title' : data.get('Title'),
      'year' : data.get('Year'),
      'director' : data.get('Director'),
      'imdbRating' : data.get('imdbRating'),
      'genre' : data.get('Genre'),
  })

pprint.pprint(movies)

df = pd.DataFrame(movies)
display(df)

[('The Avengers', '2012'), ('Avengers: Endgame', '2019'), ('Avengers: Infinity War', '2018'), ('Avengers: Age of Ultron', '2015')]
[{'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg',
  'Title': 'The Avengers',
  'Type': 'movie',
  'Year': '2012',
  'imdbID': 'tt0848228'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg',
  'Title': 'Avengers: Endgame',
  'Type': 'movie',
  'Year': '2019',
  'imdbID': 'tt4154796'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg',
  'Title': 'Avengers: Infinity War',
  'Type': 'movie',
  'Year': '2018',
  'imdbID': 'tt4154756'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BODBhYTg1NGQtNGVmNS00ZTdiLThjYTYtZDFkNzRiNTZmNDZjXkEyXkFqcGc@._V1_SX300.jpg',
  'Title': 'Avengers: Age of Ultron',
  'Type': 'movie',
  'Year': '2015',
  'imdbID': 'tt2395427'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BZTA4ZmZlZWQtZDRlYS00ZWZhLTk0MzEtYjExMGIzMTBlZDNlXkEyXkFqcGc@._V1_SX300.jpg',
  'Title': 'The Avengers',
  'Type': 'movie',
  'Year': '1998',
  'imdbID': 'tt0118661'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTYyMjk0NTMwMl5BMl5BanBnXkFtZTgwNzY0NjAwNzE@._V1_SX300.jpg',
  'Title': 'Ultimate Avengers: The Movie',
  'Type': 'movie',
  'Year': '2006',
  'imdbID': 'tt0491703'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BZjI3MTI5ZTYtZmNmNy00OGZmLTlhNWMtNjZiYmYzNDhlOGRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
  'Title': 'Ultimate Avengers II',
  'Type': 'movie',
  'Year': '2006',
  'imdbID': 'tt0803093'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTQ3NjExNjY4N15BMl5BanBnXkFtZTcwNTczODkwNQ@@._V1_SX300.jpg',
  'Title': 'Next Avengers: Heroes of Tomorrow',
  'Type': 'movie',
  'Year': '2008',
  'imdbID': 'tt1259998'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTU2MDg0Njk4MF5BMl5BanBnXkFtZTgwMTY0OTIyMTE@._V1_SX300.jpg',
  'Title': 'Avengers Confidential: Black Widow & Punisher',
  'Type': 'movie',
  'Year': '2014',
  'imdbID': 'tt3482378'},
 {'Poster': 'https://m.media-amazon.com/images/M/MV5BYjU2ODU5NzMtMzQ2NC00MmI5LWI1NjMtNmRmMjMzOTMxNWZhXkEyXkFqcGc@._V1_SX300.jpg',
  'Title': 'Crippled Avengers',
  'Type': 'movie',
  'Year': '1978',
  'imdbID': 'tt0077292'}]

,Title,Year,imdbID,Type,Poster
0,The Avengers,2012,tt0848228,movie,https://m.media-amazon.com/images/M/MV5BNGE0YT...
1,Avengers: Endgame,2019,tt4154796,movie,https://m.media-amazon.com/images/M/MV5BMTc5MD...
2,Avengers: Infinity War,2018,tt4154756,movie,https://m.media-amazon.com/images/M/MV5BMjMxNj...
3,Avengers: Age of Ultron,2015,tt2395427,movie,https://m.media-amazon.com/images/M/MV5BODBhYT...
4,The Avengers,1998,tt0118661,movie,https://m.media-amazon.com/images/M/MV5BZTA4Zm...
5,Ultimate Avengers: The Movie,2006,tt0491703,movie,https://m.media-amazon.com/images/M/MV5BMTYyMj...
6,Ultimate Avengers II,2006,tt0803093,movie,https://m.media-amazon.com/images/M/MV5BZjI3MT...
7,Next Avengers: Heroes of Tomorrow,2008,tt1259998,movie,https://m.media-amazon.com/images/M/MV5BMTQ3Nj...
8,Avengers Confidential: Black Widow & Punisher,2014,tt3482378,movie,https://m.media-amazon.com/images/M/MV5BMTU2MD...
9,Crippled Avengers,1978,tt0077292,movie,https://m.media-amazon.com/images/M/MV5BYjU2OD...

In [ ]:
df_sorted = df.sort_values(by='imdbRating', ascending=False)
display(df_sorted)

In [ ]:
import requests
# 상섬전자 종목 코드 005930
# https://finance.naver.com/item/main.naver?code=005930

# 하이닉스 종목 코드 000660
# https://finance.naver.com/item/main.naver?code=000660

In [ ]:
import requests
code = "005930"
url = "https://finance.naver.com/item/main/naver?code={}"

response = requests.get(url.format(code))
response.encoding = "euc-kr" # 담당 텍스트의 인코딩을 'euc-kr'로 변경
print(response.text)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<title>���̹� :: ������ ��� ����, ���̹�</title>

<style type="text/css">
.error_content * {margin:0;padding:0;}
.error_content img{border:none;}
.error_content em {font-style:normal;}
.error_content {width:410px; margin:80px auto 0; padding:57px 0 0 0; font-size:12px; font-family:"��������", "NanumGothic", "����", Dotum, AppleGothic, Sans-serif; text-align:left; line-height:14px; background:url(https://ssl.pstatic.net/static/common/error/090610/bg_thumb.gif) no-repeat center top; white-space:nowrap;}
.error_content p{margin:0;}
.error_content .error_desc {margin-bottom:21px; overflow:hidden; text-align:center;}
.error_content .error_desc2 {margin-bottom:11px; padding-bottom:7px; color:#888; line-height:18px; border-bottom:1px solid #eee;}
.error_content .error_desc3 {clear:both; color:#888;}
.error_content .error_desc3 a {color:#004790; text-decoration:underline;}
.error_content .error_list_type {clear:both; float:left; width:410px; _width:428px; margin:0 0 18px 0; *margin:0 0 7px 0; padding-bottom:13px; font-size:13px; color:#000; line-height:18px; border-bottom:1px solid #eee;}
.error_content .error_list_type dt {float:left; width:60px; _width /**/:70px; padding-left:10px; background:url(https://ssl.pstatic.net/static/common/error/090610/bg_dot.gif) no-repeat 2px 8px;}
.error_content .error_list_type dd {float:left; width:336px; _width /**/:340px; padding:0 0 0 4px;}
.error_content .error_list_type dd span {color:#339900; letter-spacing:0;}
.error_content .error_list_type dd a{color:#339900;}
.error_content p.btn{margin:29px 0 100px; text-align:center;}
</style>
</head>
<!-- ERROR -->
<body>
<div class="error_content">
	<p class="error_desc"><img src="https://ssl.pstatic.net/static/common/error/090610/txt_desc5.gif" width="319" height="30" alt="�������� ã�� �� �����ϴ�."></p>
	<p class="error_desc2">�湮�Ͻ÷��� �������� �ּҰ� �߸� �ԷµǾ��ų�,<br>
		�������� �ּҰ� ���� Ȥ�� �����Ǿ� ��û�Ͻ� �������� ã�� �� �����ϴ�.<br>
		�Է��Ͻ� �ּҰ� ��Ȯ���� �ٽ� �ѹ� Ȯ���� �ֽñ� �ٶ��ϴ�.
	</p>
	<p class="error_desc3">���� ���ǻ����� <a href="https://help.pay.naver.com" target="_blank">��������</a>�� �˷��ֽø� ģ���� �ȳ��ص帮�ڽ��ϴ�. �����մϴ�.</p>
	<p class="btn">
		<a href="javascript:history.back()"><img src="https://ssl.pstatic.net/static/common/error/090610/btn_prevpage.gif" width="115" height="35" alt="���� ��������"></a>
		<a href="https://finance.naver.com"><img src="https://ssl.pstatic.net/static/nfinance/btn_home.gif" width="115" height="35" alt="����Ȩ����"></a>
	</p>
</div>
</body>
</html>

In [ ]:
from bs4 import BeautifulSoup # html 및 xml 파일을 피싱

soup = BeautifulSoup(response.text, "html.parser") #응답 HTML을 파싱하여 soup 객체 새서

In [5]:
#현재가 태그 찾기
price_tag = soup.find('p', attrs={'class' : 'no_today'})
current_price = price_tag.find('span', attrs={'class' : 'blind'}).get_text()
print(f"현재가: {current_price}")

NameError: name 'soup' is not defined

In [ ]:
from numpy import info
# 시세 테이블 찾기
info.table = soup.find('table', attrs={'class' : 'no_info'})
td_list = info_table.find_all('td')

for td in td_list
lable = td.find('span', attrs={'class' : 'blind'})